CREATE TABLE [dbo].[ChiTietDichVu]
(
[MaThu] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MaDV] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SoLuong] [int] NULL,
[Total] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ChiTietDichVu] ADD CONSTRAINT [pk_DV] PRIMARY KEY CLUSTERED  ([MaThu], [MaDV]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ChiTietDichVu] ADD CONSTRAINT [FK__ChiTietDic__MaDV__17F790F9] FOREIGN KEY ([MaDV]) REFERENCES [dbo].[DichVu] ([MaDV]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[ChiTietDichVu] ADD CONSTRAINT [FK__ChiTietDi__MaThu__17036CC0] FOREIGN KEY ([MaThu]) REFERENCES [dbo].[QuanLyThuTien] ([MaThu]) ON DELETE CASCADE ON UPDATE CASCADE
GO
