CREATE TABLE [dbo].[HoaDonDichVu]
(
[MaHD] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MaPT] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NgayThu] [date] NULL,
[TongTien] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HoaDonDichVu] ADD CONSTRAINT [PK__HoaDonDi__2725A6E0BE25F272] PRIMARY KEY CLUSTERED  ([MaHD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HoaDonDichVu] ADD CONSTRAINT [FK__HoaDonDich__MaPT__01142BA1] FOREIGN KEY ([MaPT]) REFERENCES [dbo].[HopDongThuePhong] ([MaThue]) ON DELETE CASCADE ON UPDATE CASCADE
GO
