CREATE TABLE [dbo].[DichVu]
(
[MaDV] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DonViTinh] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GiaTien] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DichVu] ADD CONSTRAINT [PK__DichVu__272586579F31561F] PRIMARY KEY CLUSTERED  ([MaDV]) ON [PRIMARY]
GO
