CREATE TABLE [dbo].[ChiTietHoaDon]
(
[MaHD] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MaDV] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SoLuong] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ChiTietHoaDon] ADD CONSTRAINT [pk_ChiTiet] PRIMARY KEY CLUSTERED  ([MaHD], [MaDV]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ChiTietHoaDon] ADD CONSTRAINT [FK__ChiTietHoa__MaDV__46E78A0C] FOREIGN KEY ([MaDV]) REFERENCES [dbo].[DichVu] ([MaDV]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[ChiTietHoaDon] ADD CONSTRAINT [FK__ChiTietHoa__MaHD__45F365D3] FOREIGN KEY ([MaHD]) REFERENCES [dbo].[HoaDon] ([MaHD]) ON DELETE CASCADE ON UPDATE CASCADE
GO
