CREATE TABLE [dbo].[ChiTietHoaDon]
(
[MaDV] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MaHD] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SoLuong] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ChiTietHoaDon] ADD CONSTRAINT [pk_dv] PRIMARY KEY CLUSTERED  ([MaDV], [MaHD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ChiTietHoaDon] ADD CONSTRAINT [FK__ChiTietHoa__MaDV__2EDAF651] FOREIGN KEY ([MaDV]) REFERENCES [dbo].[DichVu] ([MaDV]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[ChiTietHoaDon] ADD CONSTRAINT [FK__ChiTietHoa__MaHD__2FCF1A8A] FOREIGN KEY ([MaHD]) REFERENCES [dbo].[HoaDonDichVu] ([MaHD]) ON DELETE CASCADE ON UPDATE CASCADE
GO
